In [1]:
import numpy as np

In [7]:
lst = [1,-2,-3,4,5,6]

In [18]:
lst # list
type(arr)
lst + lst + lst

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

In [25]:
data1=[6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [24]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [32]:
arr1.dtype

dtype('float64')

In [33]:
data2 = [[1,2,3,4,],[5,6,7,8,]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr1.ndim #속성임.. 괄호가 없음.

1

In [40]:
arr1.shape

(5,)

In [42]:
arr2.reshape((4,2)) ##reshape의경우 컴퓨팅 코스트가 전혀 들지아니함... 전혀 문제안됨. 메모리영향없음

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
arr.reshape((2,3))

array([[ 1, -2, -3],
       [ 4,  5,  6]])

In [56]:
np.zeros(150)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
result = 0
for i in range(10):
    result = 100
result

100

In [256]:
arr = np.array([[0], [3], [6, 7, 8]])
arr

TypeError: list indices must be integers or slices, not tuple

In [252]:
arr_a = np.array([[4, 5, 2], [7, 8, 9], [10, 7, 8]])
arr_a

array([list([4, 5]), list([7, 8, 9]), list([10, 7, 8])], dtype=object)

In [70]:
lst[0:5:2]

[1, -3, 5]

In [77]:
np.eye(25)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 

In [78]:
arr1 = np.array([1,2,3,], dtype=np.float32)

In [79]:
arr1

array([1., 2., 3.], dtype=float32)

In [80]:
arr2 = np.array([1,2,3], dtype=np.float64)

In [83]:
arr * 3

array([ 3, -6, -9, 12, 15, 18])

In [84]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
arr2d.ndim

2

In [88]:
arr2d[2]

array([7, 8, 9])

In [89]:
arr2d[0][2]

3

In [90]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [91]:
arr3d.ndim

3

In [93]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [109]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
arr[1:6]

array([1, 2, 3, 4, 5])

## boolean 이 은근 헷갈리는 컨셉임

In [102]:
data = np.arange(28)
data=data.reshape(7,4)

In [103]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [104]:
names = np.array(['Bob','Joe','Will','Bob', 'Will' ,'Joe', 'Joe'])

In [105]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [106]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [108]:
data[names=='Bob']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [110]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [111]:
mask = (names=='Bob')|()

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [113]:
arr = np.arange(15).reshape((3,5))

In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [116]:
arr = np.random.randn(6,3)

In [117]:
arr

array([[ 0.74035975, -0.77912571, -0.09504327],
       [ 0.78343437,  1.05269649, -0.09407108],
       [-0.08180642,  2.17123146,  0.52907835],
       [ 1.07659616, -0.03180207,  2.21005161],
       [-0.26260741,  0.78042199,  0.20802873],
       [-0.9163518 , -0.59578581,  0.24455287]])

In [118]:
import numpy as np

In [119]:
lst = [1,-2,-3,4,5,6]

In [120]:
arr = np.array(lst)

In [121]:
arr * 3

array([ 3, -6, -9, 12, 15, 18])

In [122]:
lst = [1, -2, -3, 4, 5, 6]

In [123]:
np.array(lst)

array([ 1, -2, -3,  4,  5,  6])

In [125]:
np.array(lst)

array([ 1, -2, -3,  4,  5,  6])

In [126]:
arr * 3

array([ 3, -6, -9, 12, 15, 18])

In [127]:
arr + arr

array([ 2, -4, -6,  8, 10, 12])

In [128]:
lst * 3

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

In [129]:
lst + lst

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

In [130]:
lst * 3

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

In [131]:
## 1차원 배열
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [135]:
## 2차원 배열
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
arr1.ndim
arr2.ndim

2

In [138]:
arr1.shape

(5,)

In [139]:
arr2.shape

(2, 4)

In [140]:
arr2.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [141]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [142]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
arr1.dtype

dtype('float64')

In [146]:
arr2.dtype

dtype('int32')

In [149]:
np.empty((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [150]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [151]:
arr1 = np.array([1,2,3], dtype = np.float32)

In [152]:
arr1

array([1., 2., 3.], dtype=float32)

In [153]:
arr2 = np.array([1,2,3], dtype=np.float64)

In [155]:
arr2.dtype

dtype('float64')

In [157]:
arr1.dtype, arr2.dtype

(dtype('float32'), dtype('float64'))

## 타입변경

In [159]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [160]:
arr.dtype

dtype('int32')

In [161]:
f_arr = arr.astype(np.float64)

In [162]:
f_arr

array([1., 2., 3., 4., 5.])

In [166]:
arr.dtype

dtype('int32')

In [167]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [168]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [169]:
num_str = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [170]:
num_str

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [171]:
num_str.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [172]:
emp_uint32 = np.empty(8, dtype = 'u4')

In [173]:
emp_uint32

array([3336709992,        513, 2878609904,      32762,          2,
                0, 4294967295, 4294967295], dtype=uint32)

In [174]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [175]:
arr*3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [176]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [177]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [178]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [179]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [180]:
## 인덱싱과 슬라이싱
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
arr[5]

5

In [196]:
arr[5:8] = 33

In [197]:
arr

array([ 0,  1,  2,  3,  4, 33, 33, 33,  8,  9])

In [198]:
arr = np.arange(10)

In [199]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
arr_cp = arr[5:8].copy()

In [202]:
arr_cp[:] = 128

In [203]:
arr_cp

array([128, 128, 128])

## 2차원 3차원 배열제어

In [207]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [208]:
arr2d.ndim

2

In [210]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [213]:
arr2d[1]

array([4, 5, 6])

In [214]:
arr2d[0,2]

3

In [215]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [216]:
arr3d.ndim

3

In [219]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [218]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
a = arr3d[0].copy
a

<function ndarray.copy>

In [224]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [227]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [229]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [230]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [231]:
arr2d[:2][1:] ##??

array([[4, 5, 6]])

In [232]:
arr2d[1, :2]

array([4, 5])

In [233]:
arr2d[2, :1]

array([7])

In [234]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [236]:
arr2d[:2, 1:] =0

In [237]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [239]:
points = np.arange(10000, dtype='f')
points[:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [240]:
%%time
total = 0
for i in points:
    total += i
print(total)

49995000.0
Wall time: 3.01 ms


In [243]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
import numpy as np

# scikit-learn 패키지의 metrics 모듈에서 make_scorer라는 함수를 가지고 옵니다.
# 이 함수는 파이썬을 구현한 측정 공식을 scikit-learn에서 사용할 수 있도록 변환해 줍니다.
from sklearn.metrics import make_scorer

# RMSLE 공식을 구현한 함수를 생성합니다.
# 이 함수는 예측값(predict)과 정답(actual)을 인자로 받습니다.
def rmsle(predict, actual):
    # predict와 actual을 numpy array로 변환합니다.
    # 이렇게 하면 수학 연산을 편하게 할 수 있습니다.
    predict = np.array(predict)
    actual = np.array(actual)
    
    # 공식에 쓰여진대로 predict와 actual에 log(count + 1)을 합니다.
    # 이 결과를 각각 log_predict와 log_actual에 대입합니다.
    log_predict = np.log(predict + 1)
    log_actual = np.log(actual + 1)
    
    # 공식에 쓰여진대로 log_predict와 log_actual을 빼서 차이를 구합니다.
    # 이 차이를 distance라는 이름의 새로운 변수에 할당합니다.
    distance = log_predict - log_actual
    
    # 공식에 쓰여진대로 distance를 제곱합니다.
    # 이 결과를 square_distance라는 이름의 새로운 변수에 할당합니다.
    square_distance = distance ** 2
    
    # 공식에 쓰여진대로 square_distance의 평균을 구합니다.
    # 이 결과를 mean_square_distance라는 이름의 새로운 변수에 할당합니다.
    mean_square_distance = square_distance.mean()
    
    # 공식에 쓰여진대로 mean_square_distance에 루트(sqrt)를 씌웁니다.
    # 이 결과를 score라는 이름의 새로운 변수에 할당합니다.
    score = np.sqrt(mean_square_distance)
    
    # score 변수를 반환합니다.
    return score

# scikit-learn의 make_scorer를 활용하여
# rmsle 함수를 scikit-learn의 다른 함수에서 사용할 수 있도록 변환합니다.
# 이 결과를 rmsle_score라는 이름의 새로운 변수에 할당합니다.
rmsle_score = make_scorer(rmsle)
rmsle_score

In [ ]:
# scikit-learn의 model_selection 모듈에서 cross_val_score 함수를 가져옵니다.
# 이 함수는 Cross Validation의 모든 기능을 한 번에 실행합니다.
from sklearn.model_selection import cross_val_score

# cross_val_score를 실행합니다. 실행할 때는 다음의 옵션이 들어갑니다.
# 1) model. 점수를 측정할 머신러닝 모델(현재는 Random Forest)이 들어갑니다.
# 2) X_train. train 데이터의 feature 입니다.
# 3) y_train. train 데이터의 label 입니다.
# 4) cv. Cross Validation에서 데이터를 조각낼(split) 갯수입니다. 총 20조각을 내야하기 때문에 20을 대입합니다.
# 5) scoring. 점수를 측정할 공식입니다. 앞서 구현한 RMSLE를 적용합니다.
# 마지막으로, 이 함수의 실행 결과의 평균(mean)을 구한 뒤 score라는 이름의 새로운 변수에 할당합니다.
score = cross_val_score(model, X_train, y_train,
                        cv=20, scoring=rmsle_score).mean()

# score 변수에 할당한 점수를 출력합니다.
print("Score = {0:.5f}".format(score))

In [ ]:
# scikit-learn 패키지의 ensemble 모듈에 있는 RandomForestRegressor를 가지고 옵니다.
from sklearn.ensemble import RandomForestRegressor

# RandomForestRegressor를 생성합니다. 실행할 때는 다음의 옵션이 들어갑니다.
# 1) n_jobs. 병렬처리 여부입니다. -1을 대입하면 컴퓨터에 존재하는 모든 코어(Core, ex: 듀얼코어, 쿼드코어)를 전부 활용합니다.
# 2) random_state. 랜덤포레스트의 결과가 랜덤하게 나오는 것을 고정하는 옵션입니다. 아무 숫자나 넣어주면 됩니다. (공학 용어에서 쓰이는 Seed Number와 동일한 개념입니다)
model = RandomForestRegressor(n_jobs=-1,random_state=37)
model

In [ ]:
##Model Fitting
model.fit(X_train, y_train)

## Predict

In [ ]:
predictions = model.predict(X_test)

# predictions 변수에 할당된 데이터의 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시되나, column이 없기 때문에 (row,) 형태로 표시될 것입니다.
print(predictions.shape)

# predictions 변수를 출력합니다.
predictions

## Submission

In [ ]:
# 데이콘이 제공하는 제출 포멧(sampleSubmission.csv)을 읽어옵니다.
# 이를 submission 이라는 이름의 변수에 할당합니다.
submission = pd.read_csv("../jikbang/submission.csv")
# submission 변수에 할당된 데이터의 행렬 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시됩니다.
print(submission.shape)

# submission 데이터의 상위 5개를 띄웁니다.
submission.head()

In [ ]:
# 제출 포맷(submission)의 실거래가(transaction_real_price) 컬럼에 우리의 예측값(predictions)를 집어넣습니다.
submission["transaction_real_price"] = predictions

# submission 변수에 할당된 데이터의 행렬 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시됩니다.
print(submission.shape)

# submission 데이터의 상위 5개를 띄웁니다.
submission.head()

## submission 파일이 저장되었습니다. Dacon 게시판에 업로드 후 스코어 체크!